version: "3.8"

services:
  db:
    image: postgres:15
    container_name: bakery_db
    restart: always
    environment:
      POSTGRES_USER: bakery_user
      POSTGRES_PASSWORD: bakery_pass
      POSTGRES_DB: bakery_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init_products.sql:/docker-entrypoint-initdb.d/01_init_products.sql:ro
    networks:
      - bakery-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bakery_user"]
      interval: 30s
      timeout: 5s
      retries: 5

    # Local Compose resource constraints
    mem_limit: 512m
    cpus: "0.5"

    # Swarm/K8s compatible definition
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bakery_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bakery-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

    mem_limit: 512m
    cpus: "1.0"

    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          cpus: "0.50"
          memory: 256M

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bakery_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bakery-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 30s
      timeout: 30s
      retries: 8

    mem_limit: 256m
    cpus: "0.5"

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8000
    container_name: bakery_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - bakery-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

    mem_limit: 256m
    cpus: "0.5"

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

volumes:
  db_data:

networks:
  bakery-network:
    driver: bridge
